remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# theme: minima
title: "[redacted] GUIDELINES MAIN PAGE TITLE"
# author: authored by [redacted], reviewed and revised by [redacted] and [redacted] # for minima theme
description: description [redacted]
